// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiRNpkBQNQIzINLab3q9QW3cztDwo77fM',
    appId: '1:617330242189:web:2264b7d5b517373e47e8c4',
    messagingSenderId: '617330242189',
    projectId: 'code-can-1438d',
    authDomain: 'code-can-1438d.firebaseapp.com',
    storageBucket: 'code-can-1438d.appspot.com',
    measurementId: 'G-FYVCS56D2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxuWnZ5XfLP653hWxRrRMOhGHtlug8mk',
    appId: '1:617330242189:android:cbe0e0e2a21a1e9e47e8c4',
    messagingSenderId: '617330242189',
    projectId: 'code-can-1438d',
    storageBucket: 'code-can-1438d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN12scpc8yPfZMvqjiBvHXrYmECCRV9oA',
    appId: '1:617330242189:ios:50d80aaa7e25b0d347e8c4',
    messagingSenderId: '617330242189',
    projectId: 'code-can-1438d',
    storageBucket: 'code-can-1438d.appspot.com',
    iosBundleId: 'com.example.codecansecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN12scpc8yPfZMvqjiBvHXrYmECCRV9oA',
    appId: '1:617330242189:ios:1d5eee95ab93cdb247e8c4',
    messagingSenderId: '617330242189',
    projectId: 'code-can-1438d',
    storageBucket: 'code-can-1438d.appspot.com',
    iosBundleId: 'com.example.codecansecond.RunnerTests',
  );
}
